name: Enrich KEV

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  enrich-kev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Scripts
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install Python Dependencies
        run: python -m pip install --upgrade pip pandas
      - name: Install SQLite3
        run: |
          sudo apt update
          sudo apt install sqlite3
      - name: Fetch KEV
        run: curl -o ./known_exploited_vulnerabilities.csv https://www.cisa.gov/sites/default/files/csv/known_exploited_vulnerabilities.csv
      - name: Fetch NVD
        uses: docker://vuls/go-cve-dictionary:latest
        with:
          entrypoint: '/bin/sh'
          args: '-c "go-cve-dictionary fetch nvd | sleep 15"'
      - name: 'Extract CPE from NVD'
        run: sqlite3 ./cve.sqlite3 ".header on" ".mode csv" "select nvds.cve_id, nvd_cpes.uri from nvd_cpes LEFT JOIN nvds ON nvd_cpes.nvd_id = nvds.id;" > ./nvd_cpes.csv
      - name: Merge KEV with CPE
        run: python ./kev_enricher.py
      - name: Set ENV
        env:
          TZ: Asia/Tokyo
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: Release Enriched KEV
        uses: softprops/action-gh-release@v2
        with:
          files: ./known_exploited_vulnerabilities_with_cpes.csv
          tag_name: Nightly
          body: "Final Updated at ${{ env.CURRENT_DATETIME }}."
